version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: adminmusic
      POSTGRES_PASSWORD: adminmusic
      POSTGRES_DB: musical-encyclopedia-database
    ports:
      - "6543:6543"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
